// <auto-generated />
// This file was generated by R4Mvc.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the r4mvc.json file (i.e. the settings file), save it and run the generator tool again.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo.Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
#pragma warning disable 1591, 3008, 3009, 0108
using System.CodeDom.Compiler;
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using R4Mvc;

[GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
public static partial class MVC
{
    static readonly R4Mvc.ManageAreaClass s_Manage = new R4Mvc.ManageAreaClass();
    public static R4Mvc.ManageAreaClass Manage => s_Manage;
    public static readonly ContentManagement.Controllers.ByController By = new ContentManagement.Controllers.R4MVC_ByController();
    public static readonly ContentManagement.Controllers.ErrorController Error = new ContentManagement.Controllers.R4MVC_ErrorController();
    public static readonly ContentManagement.Controllers.HomeController Home = new ContentManagement.Controllers.R4MVC_HomeController();
    public static readonly ContentManagement.Controllers.LanguageController Language = new ContentManagement.Controllers.R4MVC_LanguageController();
    public static readonly ContentManagement.Controllers.LoginController Login = new ContentManagement.Controllers.R4MVC_LoginController();
    public static readonly R4Mvc.SharedController Shared = new R4Mvc.SharedController();
}

namespace R4Mvc
{
    [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
    public class Dummy
    {
        private Dummy()
        {
        }

        public static Dummy Instance = new Dummy();
    }

    [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
    public partial class SharedController
    {
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames => s_ViewNames;
            public class _ViewNamesClass
            {
                public readonly string AccessDenied = "AccessDenied";
                public readonly string Error = "Error";
                public readonly string NotFound = "NotFound";
                public readonly string _CustomValidationSummary = "_CustomValidationSummary";
            }

            public readonly string AccessDenied = "~/Views/Shared/AccessDenied.cshtml";
            public readonly string Error = "~/Views/Shared/Error.cshtml";
            public readonly string NotFound = "~/Views/Shared/NotFound.cshtml";
            public readonly string _CustomValidationSummary = "~/Views/Shared/_CustomValidationSummary.cshtml";
        }

        static readonly ViewsClass s_Views = new ViewsClass();
        public ViewsClass Views => s_Views;
    }

    [GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
    public partial class ManageAreaClass
    {
        public readonly string Name = "Manage";
        public readonly ContentManagement.Areas.Manage.Controllers.ChangePasswordController ChangePassword = new ContentManagement.Areas.Manage.Controllers.R4MVC_ChangePasswordController();
        public readonly ContentManagement.Areas.Manage.Controllers.HomeController Home = new ContentManagement.Areas.Manage.Controllers.R4MVC_HomeController();
        public readonly ContentManagement.Areas.Manage.Controllers.PortalController Portal = new ContentManagement.Areas.Manage.Controllers.R4MVC_PortalController();
    }
}

[GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
public static partial class Links
{
    public static partial class css
    {
        public static string common_min_css = "~/css/common.min.css";
        public static string ltr_min_css = "~/css/ltr.min.css";
        public static string manage_min_css = "~/css/manage.min.css";
        public static string rtl_min_css = "~/css/rtl.min.css";
    }

    public static partial class fonts
    {
        public static string farsifonts_min_css = "~/fonts/farsifonts.min.css";
        public static string fontawesome_webfont_eot = "~/fonts/fontawesome-webfont.eot";
        public static string fontawesome_webfont_svg = "~/fonts/fontawesome-webfont.svg";
        public static string fontawesome_webfont_ttf = "~/fonts/fontawesome-webfont.ttf";
        public static string fontawesome_webfont_woff = "~/fonts/fontawesome-webfont.woff";
        public static string fontawesome_webfont_woff2 = "~/fonts/fontawesome-webfont.woff2";
        public static string FontAwesome_otf = "~/fonts/FontAwesome.otf";
        public static string Shabnam_Bold_eot = "~/fonts/Shabnam-Bold.eot";
        public static string Shabnam_Bold_ttf = "~/fonts/Shabnam-Bold.ttf";
        public static string Shabnam_Bold_woff = "~/fonts/Shabnam-Bold.woff";
        public static string Shabnam_Bold_woff2 = "~/fonts/Shabnam-Bold.woff2";
        public static string Shabnam_Light_eot = "~/fonts/Shabnam-Light.eot";
        public static string Shabnam_Light_ttf = "~/fonts/Shabnam-Light.ttf";
        public static string Shabnam_Light_woff = "~/fonts/Shabnam-Light.woff";
        public static string Shabnam_Light_woff2 = "~/fonts/Shabnam-Light.woff2";
        public static string Shabnam_eot = "~/fonts/Shabnam.eot";
        public static string Shabnam_ttf = "~/fonts/Shabnam.ttf";
        public static string Shabnam_woff = "~/fonts/Shabnam.woff";
        public static string Shabnam_woff2 = "~/fonts/Shabnam.woff2";
        public static string Vazir_Bold_eot = "~/fonts/Vazir-Bold.eot";
        public static string Vazir_Bold_ttf = "~/fonts/Vazir-Bold.ttf";
        public static string Vazir_Bold_woff = "~/fonts/Vazir-Bold.woff";
        public static string Vazir_Bold_woff2 = "~/fonts/Vazir-Bold.woff2";
        public static string Vazir_Light_eot = "~/fonts/Vazir-Light.eot";
        public static string Vazir_Light_ttf = "~/fonts/Vazir-Light.ttf";
        public static string Vazir_Light_woff = "~/fonts/Vazir-Light.woff";
        public static string Vazir_Light_woff2 = "~/fonts/Vazir-Light.woff2";
        public static string Vazir_Medium_eot = "~/fonts/Vazir-Medium.eot";
        public static string Vazir_Medium_ttf = "~/fonts/Vazir-Medium.ttf";
        public static string Vazir_Medium_woff = "~/fonts/Vazir-Medium.woff";
        public static string Vazir_Medium_woff2 = "~/fonts/Vazir-Medium.woff2";
        public static string Vazir_Thin_eot = "~/fonts/Vazir-Thin.eot";
        public static string Vazir_Thin_ttf = "~/fonts/Vazir-Thin.ttf";
        public static string Vazir_Thin_woff = "~/fonts/Vazir-Thin.woff";
        public static string Vazir_Thin_woff2 = "~/fonts/Vazir-Thin.woff2";
        public static string Vazir_eot = "~/fonts/Vazir.eot";
        public static string Vazir_ttf = "~/fonts/Vazir.ttf";
        public static string Vazir_woff = "~/fonts/Vazir.woff";
        public static string Vazir_woff2 = "~/fonts/Vazir.woff2";
    }

    public static partial class js
    {
        public static string common_min_js = "~/js/common.min.js";
        public static string manage_min_js = "~/js/manage.min.js";
    }

    public static partial class statics
    {
        public static string Datatable_Persian_json = "~/statics/Datatable.Persian.json";
        public static string login_css = "~/statics/login.css";
        public static string login_js = "~/statics/login.js";
        public static string logo_png = "~/statics/logo.png";
        public static string NoScript_html = "~/statics/NoScript.html";
    }

    public static string favicon_ico = "~/favicon.ico";
    public static string favicon_png = "~/favicon.png";
}

[GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
internal partial class R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult : ActionResult, IR4MvcActionResult
{
    public R4Mvc_Microsoft_AspNetCore_Mvc_ActionResult(string area, string controller, string action, string protocol = null)
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }

    public string Controller
    {
        get;
        set;
    }

    public string Action
    {
        get;
        set;
    }

    public string Protocol
    {
        get;
        set;
    }

    public RouteValueDictionary RouteValueDictionary
    {
        get;
        set;
    }
}

[GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
internal partial class R4Mvc_Microsoft_AspNetCore_Mvc_JsonResult : JsonResult, IR4MvcActionResult
{
    public R4Mvc_Microsoft_AspNetCore_Mvc_JsonResult(string area, string controller, string action, string protocol = null): base (null)
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }

    public string Controller
    {
        get;
        set;
    }

    public string Action
    {
        get;
        set;
    }

    public string Protocol
    {
        get;
        set;
    }

    public RouteValueDictionary RouteValueDictionary
    {
        get;
        set;
    }
}

[GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
internal partial class R4Mvc_Microsoft_AspNetCore_Mvc_ContentResult : ContentResult, IR4MvcActionResult
{
    public R4Mvc_Microsoft_AspNetCore_Mvc_ContentResult(string area, string controller, string action, string protocol = null)
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }

    public string Controller
    {
        get;
        set;
    }

    public string Action
    {
        get;
        set;
    }

    public string Protocol
    {
        get;
        set;
    }

    public RouteValueDictionary RouteValueDictionary
    {
        get;
        set;
    }
}

[GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
internal partial class R4Mvc_Microsoft_AspNetCore_Mvc_FileResult : FileResult, IR4MvcActionResult
{
    public R4Mvc_Microsoft_AspNetCore_Mvc_FileResult(string area, string controller, string action, string protocol = null): base (null)
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }

    public string Controller
    {
        get;
        set;
    }

    public string Action
    {
        get;
        set;
    }

    public string Protocol
    {
        get;
        set;
    }

    public RouteValueDictionary RouteValueDictionary
    {
        get;
        set;
    }
}

[GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
internal partial class R4Mvc_Microsoft_AspNetCore_Mvc_RedirectResult : RedirectResult, IR4MvcActionResult
{
    public R4Mvc_Microsoft_AspNetCore_Mvc_RedirectResult(string area, string controller, string action, string protocol = null): base (" ")
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }

    public string Controller
    {
        get;
        set;
    }

    public string Action
    {
        get;
        set;
    }

    public string Protocol
    {
        get;
        set;
    }

    public RouteValueDictionary RouteValueDictionary
    {
        get;
        set;
    }
}

[GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
internal partial class R4Mvc_Microsoft_AspNetCore_Mvc_RedirectToActionResult : RedirectToActionResult, IR4MvcActionResult
{
    public R4Mvc_Microsoft_AspNetCore_Mvc_RedirectToActionResult(string area, string controller, string action, string protocol = null): base (" ", " ", " ")
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }

    public string Controller
    {
        get;
        set;
    }

    public string Action
    {
        get;
        set;
    }

    public string Protocol
    {
        get;
        set;
    }

    public RouteValueDictionary RouteValueDictionary
    {
        get;
        set;
    }
}

[GeneratedCode("R4Mvc", "1.0"), DebuggerNonUserCode]
internal partial class R4Mvc_Microsoft_AspNetCore_Mvc_RedirectToRouteResult : RedirectToRouteResult, IR4MvcActionResult
{
    public R4Mvc_Microsoft_AspNetCore_Mvc_RedirectToRouteResult(string area, string controller, string action, string protocol = null): base (null)
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }

    public string Controller
    {
        get;
        set;
    }

    public string Action
    {
        get;
        set;
    }

    public string Protocol
    {
        get;
        set;
    }

    public RouteValueDictionary RouteValueDictionary
    {
        get;
        set;
    }
}
#pragma warning restore 1591, 3008, 3009, 0108
